# Generated by Django 6.0.3 on 2026-03-26 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escudo', models.URLField(blank=True, max_length=500, null=True)),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('empates', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('gols_pro', models.PositiveIntegerField(default=0)),
                ('gols_contra', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
                ('gols', models.PositiveIntegerField(default=0)),
                ('cartoes_amarelos', models.PositiveIntegerField(default=0)),
                ('cartoes_vermelhos', models.PositiveIntegerField(default=0)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='torneio.time')),
            ],
        ),
    ]
