# Generated by Django 6.0.3 on 2026-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0002_partida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_torneio', models.CharField(default='Copa Área 7', max_length=100)),
                ('youtube_live_id', models.CharField(blank=True, help_text='Insira apenas o ID do vídeo (ex: dQw4w9WgXcQ)', max_length=20)),
                ('esta_ao_vivo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configuração Geral',
            },
        ),
    ]
