# Generated by Django 6.0.3 on 2026-03-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0003_configuracaogeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='playlist_id',
            field=models.CharField(blank=True, help_text='ID da Playlist de Melhores Momentos (ex: PLir...)', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='youtube_live_id',
            field=models.CharField(blank=True, help_text='ID do vídeo da LIVE (ex: dQw4w9WgXcQ)', max_length=20),
        ),
    ]
