# Generated by Django 6.0.3 on 2026-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0004_configuracaogeral_playlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='proxima_live',
            field=models.DateTimeField(blank=True, help_text='Data e hora da próxima transmissão', null=True),
        ),
    ]
