# Generated by Django 6.0.3 on 2026-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0005_configuracaogeral_proxima_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título/Legenda')),
                ('imagem_url', models.URLField(help_text='Cole o link da imagem (ex: do Instagram ou Imgur)', max_length=500)),
                ('link_post', models.URLField(blank=True, help_text='Link para o post original (opcional)', max_length=500)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Galeria de Fotos',
                'ordering': ['ordem', '-id'],
            },
        ),
    ]
