# Generated by Django 6.0.3 on 2026-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0006_fotogaleria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['data_partida'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AddField(
            model_name='partida',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Partida Encerrada?'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='playlist_id',
            field=models.CharField(blank=True, help_text='ID da Playlist', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='proxima_live',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='youtube_live_id',
            field=models.CharField(blank=True, help_text='ID do vídeo da LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='imagem_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='link_post',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data_partida',
            field=models.DateTimeField(verbose_name='Data e Hora do Jogo'),
        ),
    ]
